spring:
  datasource:
    url: jdbc:mysql://localhost:3308/learning_management_system?createDatabaseIfNotExist=true
    username: root
    password: nethmi

  jpa:
    hibernate:
      ddl-auto: update

debug: true